In [1]:
import numpy as np
import pandas as pd

In [2]:
ruta_base = './archivos/'
archivo = 'respuestos_ford.csv'
df = pd.read_csv(ruta_base+archivo)
df.head()

,hfpxzc href,qBF1Pd,W4Efsd,W4Efsd 3,UsdlK
0,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN
2,https://www.google.com.ar/maps/place/Megaford/...,Megaford,Tienda de repuestos para automóvil,4435 Avenida Juan B Justo,0351 858-0800
3,https://www.google.com.ar/maps/place/Maip%C3%B...,Maipú Ford,Concesionario Ford,·,0351 485-9500
4,https://www.google.com.ar/maps/place/FORD+COLO...,FORD COLON,Tienda de repuestos para automóvil,Av. Colón 2855,0351 489-7236

In [3]:
elim = [0, 2]
df = df.drop(df.columns[elim], axis=1)

# df = df.iloc[:,1:]
# df2 = df[1]
# df2.head()
df

                  qBF1Pd                        W4Efsd 3          UsdlK
0                    NaN                             NaN            NaN
1                    NaN                             NaN            NaN
2               Megaford       4435 Avenida Juan B Justo  0351 858-0800
3             Maipú Ford                               ·  0351 485-9500
4             FORD COLON                  Av. Colón 2855  0351 489-7236
..                   ...                             ...            ...
120        GCB Repuestos        Av. Leandro N. Alem 2295  0351 559-4271
121    Repuestos Urquiza  Tte. Gral. Donato Alvarez 7383            NaN
122            Delga Srl                    Hualfin 1050  0351 473-9545
123  Repuestos O'Higgins                               ·  0351 399-3324
124                  NaN                             NaN            NaN

[125 rows x 3 columns]

In [4]:
# 1. Verificar valores nulos
nulos = df.isnull()
# 2. Verificar longitud <4 para no nulos
cortos = df.apply(lambda col: col.dropna().astype(str).str.len() < 5)
# Combinar condiciones
df['es_invalida'] = (nulos.all(axis=1) | cortos.all(axis=1))
df

,qBF1Pd,W4Efsd 3,UsdlK,es_invalida
0,NaN,NaN,NaN,True
1,NaN,NaN,NaN,True
2,Megaford,4435 Avenida Juan B Justo,0351 858-0800,False
3,Maipú Ford,·,0351 485-9500,False
4,FORD COLON,Av. Colón 2855,0351 489-7236,False
...,...,...,...,...
120,GCB Repuestos,Av. Leandro N. Alem 2295,0351 559-4271,False
121,Repuestos Urquiza,Tte. Gral. Donato Alvarez 7383,NaN,False
122,Delga Srl,Hualfin 1050,0351 473-9545,False
123,Repuestos O'Higgins,·,0351 399-3324,False
124,NaN,NaN,NaN,True

In [5]:
condicion = df.iloc[:,2].isnull() | (df.iloc[:,2].astype(str).str.len() < 10) | df.iloc[:,-1].astype(bool)
df = df[~condicion]

In [6]:
df.head(10)

,qBF1Pd,W4Efsd 3,UsdlK,es_invalida
2,Megaford,4435 Avenida Juan B Justo,0351 858-0800,False
3,Maipú Ford,·,0351 485-9500,False
4,FORD COLON,Av. Colón 2855,0351 489-7236,False
6,Maipú Ford Servicio,·,0351 485-9500,False
7,FORCOR – Concesionario Oficial [Córdoba] | For...,Juan Antonio Lavalleja 799,0351 570-4421,False
8,MF Repuestos Ford,·,0351 880-6325,False
9,Repuestos Avenida,·,0351 15-807-8844,False
10,ℱ𝓸𝓻𝓭 ESQUIU – Repuestos y Accesorios,·,0351 425-1770,False
11,Ford Alem,·,0351 474-1995,False
12,Ford Abel,Humberto 1º 840,0351 424-5048,False

In [7]:
# col = 'es_invalida'
# col = df.columns[3]
# df = df[~df[col]]
# df

In [8]:
df = df.iloc[:, :-1]
df.to_csv(f'./archivos/mod/{archivo}', index=None)