In [40]:
import numpy as np
import pandas as pd
import re

In [41]:
ruta_base = './archivos/'
sub = 'busquedas/'
query = 'const/'
archivo = 'ab.csv'
df = pd.read_csv(ruta_base+sub+query+archivo)
df.head()

,hfpxzc href,qBF1Pd,W4Efsd,W4Efsd 3,UsdlK,ah5Ghc 3
0,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN
2,https://www.google.com.ar/maps/place/Vidrios+M...,Vidrios Millicay (vidriería y aberturas de alu...,Tienda de cristales y espejos,1546 Félix Paz,0351 466-6826,NaN
3,https://www.google.com.ar/maps/place/Metalurgi...,Metalurgica Tobías,Empresa de procesamiento de metales,2626 Avenida Monseñor Pablo Cabrera,0351 677-0759,NaN
4,https://www.google.com.ar/maps/place/Grupo+Shu...,Grupo Shutó -Aberturas de PVC - REHAU,Servicio de instalación de ventanas,·,0351 619-1821,", bien hermeticas y aislantes."""

In [42]:
# eliminar datos donde no hayan telefonos
df = df.dropna(subset=['UsdlK'])
df.head(2)

,hfpxzc href,qBF1Pd,W4Efsd,W4Efsd 3,UsdlK,ah5Ghc 3
2,https://www.google.com.ar/maps/place/Vidrios+M...,Vidrios Millicay (vidriería y aberturas de alu...,Tienda de cristales y espejos,1546 Félix Paz,0351 466-6826,NaN
3,https://www.google.com.ar/maps/place/Metalurgi...,Metalurgica Tobías,Empresa de procesamiento de metales,2626 Avenida Monseñor Pablo Cabrera,0351 677-0759,NaN

In [43]:
elim = [0, 2]
df = df.drop(df.columns[elim], axis=1)

# df = df.iloc[:,1:]
# df2 = df[1]
# df2.head()
df

,qBF1Pd,W4Efsd 3,UsdlK,ah5Ghc 3
2,Vidrios Millicay (vidriería y aberturas de alu...,1546 Félix Paz,0351 466-6826,NaN
3,Metalurgica Tobías,2626 Avenida Monseñor Pablo Cabrera,0351 677-0759,NaN
4,Grupo Shutó -Aberturas de PVC - REHAU,·,0351 619-1821,", bien hermeticas y aislantes."""
5,La Banderola® – Aberturas,·,0351 634-7939,"."""
6,Vidrios y Aberturas don Bosco,Av. Don Bosco 5011,0351 557-5052,NaN
...,...,...,...,...
119,Selec Aberturas,"MITRE, Las Varillas 695",03533 15-43-1640,NaN
120,Chávez Aberturas-Amoblamientos,"Santa Clara De Asis, Dr. Arturo Capdevila 2264",0351 478-0718,NaN
121,Inmecar SRL,·,0351 499-4510,NaN
122,Noval Aberturas,·,0351 340-7744,"de alto nivel!"""
123,ALU.COM Fabrica de Aberturas y Amoblamientos -...,E. Bodereau 9576,0351 15-756-5756,NaN

In [44]:
# 1. Verificar valores nulos
nulos = df.isnull()
# 2. Verificar longitud <4 para no nulos
cortos = df.apply(lambda col: col.dropna().astype(str).str.len() < 5)
# Combinar condiciones
df['es_invalida'] = (nulos.all(axis=1) | cortos.all(axis=1))
df

,qBF1Pd,W4Efsd 3,UsdlK,ah5Ghc 3,es_invalida
2,Vidrios Millicay (vidriería y aberturas de alu...,1546 Félix Paz,0351 466-6826,NaN,False
3,Metalurgica Tobías,2626 Avenida Monseñor Pablo Cabrera,0351 677-0759,NaN,False
4,Grupo Shutó -Aberturas de PVC - REHAU,·,0351 619-1821,", bien hermeticas y aislantes.""",False
5,La Banderola® – Aberturas,·,0351 634-7939,".""",False
6,Vidrios y Aberturas don Bosco,Av. Don Bosco 5011,0351 557-5052,NaN,False
...,...,...,...,...,...
119,Selec Aberturas,"MITRE, Las Varillas 695",03533 15-43-1640,NaN,False
120,Chávez Aberturas-Amoblamientos,"Santa Clara De Asis, Dr. Arturo Capdevila 2264",0351 478-0718,NaN,False
121,Inmecar SRL,·,0351 499-4510,NaN,False
122,Noval Aberturas,·,0351 340-7744,"de alto nivel!""",False
123,ALU.COM Fabrica de Aberturas y Amoblamientos -...,E. Bodereau 9576,0351 15-756-5756,NaN,False

In [45]:
condicion = df.iloc[:,2].isnull() | (df.iloc[:,2].astype(str).str.len() < 10) | df.iloc[:,-1].astype(bool)
df = df[~condicion]

In [46]:
# df.head()

In [47]:
# col = 'es_invalida'
# col = df.columns[3]
# df = df[~df[col]]
# df

In [48]:
# arreglar numero de telefono
def arreglar_numero (num):
    return re.sub(r'\D', '', str(num))
# [df.iloc[:, 2]]
df.iloc[:, 2] = df.iloc[:, 2].apply(lambda x: arreglar_numero(x))

In [49]:
# Drop column 'ah5Ghc 3' if it exists
df = df.drop(columns=['ah5Ghc 3', 'FQ2IWe src', 'e4rVHe'], axis=1, errors='ignore')
df.head()

,qBF1Pd,W4Efsd 3,UsdlK,es_invalida
2,Vidrios Millicay (vidriería y aberturas de alu...,1546 Félix Paz,03514666826,False
3,Metalurgica Tobías,2626 Avenida Monseñor Pablo Cabrera,03516770759,False
4,Grupo Shutó -Aberturas de PVC - REHAU,·,03516191821,False
5,La Banderola® – Aberturas,·,03516347939,False
6,Vidrios y Aberturas don Bosco,Av. Don Bosco 5011,03515575052,False

In [50]:
df.head()

,qBF1Pd,W4Efsd 3,UsdlK,es_invalida
2,Vidrios Millicay (vidriería y aberturas de alu...,1546 Félix Paz,03514666826,False
3,Metalurgica Tobías,2626 Avenida Monseñor Pablo Cabrera,03516770759,False
4,Grupo Shutó -Aberturas de PVC - REHAU,·,03516191821,False
5,La Banderola® – Aberturas,·,03516347939,False
6,Vidrios y Aberturas don Bosco,Av. Don Bosco 5011,03515575052,False

In [51]:
df = df.iloc[:, :-1]
columnas_relevantes = ['nombre', 'dir', 'tlf']
df.columns = columnas_relevantes
destino = f'./archivos/{sub}{query}/mod_{archivo}'
# print(destino)
df.to_csv(destino, index=None)

In [52]:
df_result = pd.read_csv(destino)
df_result.head()

,nombre,dir,tlf
0,Vidrios Millicay (vidriería y aberturas de alu...,1546 Félix Paz,3514666826
1,Metalurgica Tobías,2626 Avenida Monseñor Pablo Cabrera,3516770759
2,Grupo Shutó -Aberturas de PVC - REHAU,·,3516191821
3,La Banderola® – Aberturas,·,3516347939
4,Vidrios y Aberturas don Bosco,Av. Don Bosco 5011,3515575052