In [52]:
import numpy as np
import pandas as pd
import re

In [53]:
ruta_base = './archivos/'
sub = 'busquedas/'
query = 'abogado/'
archivo = 'abogado.csv'
df = pd.read_csv(ruta_base+sub+query+archivo)
df.head()

,hfpxzc href,qBF1Pd,W4Efsd,W4Efsd 3,UsdlK,e4rVHe
0,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN
2,https://www.google.com.ar/maps/place/Estudio+J...,Estudio Juridico Inmobiliario Sanson & Asociados,Abogado civil,275 San Jerónimo,0351 422-5646,NaN
3,https://www.google.com.ar/maps/place/Estudio+J...,Estudio Jurídico - Laboral Dres. Españon y Bot...,Servicios legales,Sucre 135 3 1,0351 514-5620,NaN
4,https://www.google.com.ar/maps/place/Crucella+...,Crucella Estudio de Abogados,Abogado,Tristán Malbrán 3877,0351 389-7260,NaN

In [54]:
# eliminar datos donde no hayan telefonos
df = df.dropna(subset=['UsdlK'])
df.head(2)

,hfpxzc href,qBF1Pd,W4Efsd,W4Efsd 3,UsdlK,e4rVHe
2,https://www.google.com.ar/maps/place/Estudio+J...,Estudio Juridico Inmobiliario Sanson & Asociados,Abogado civil,275 San Jerónimo,0351 422-5646,NaN
3,https://www.google.com.ar/maps/place/Estudio+J...,Estudio Jurídico - Laboral Dres. Españon y Bot...,Servicios legales,Sucre 135 3 1,0351 514-5620,NaN

In [55]:
elim = [0, 2]
df = df.drop(df.columns[elim], axis=1)

# df = df.iloc[:,1:]
# df2 = df[1]
# df2.head()
df

,qBF1Pd,W4Efsd 3,UsdlK,e4rVHe
2,Estudio Juridico Inmobiliario Sanson & Asociados,275 San Jerónimo,0351 422-5646,NaN
3,Estudio Jurídico - Laboral Dres. Españon y Bot...,Sucre 135 3 1,0351 514-5620,NaN
4,Crucella Estudio de Abogados,Tristán Malbrán 3877,0351 389-7260,NaN
5,ROSSI CARRETERO Abogadas,Nicolás Berrotarán 1917 piso 2 Of c,0351 303-2267,NaN
6,ARAYA / ABOGADOS,Gdor. Roque Ferreyra 1506,0351 804-2406,NaN
...,...,...,...,...
120,Jubilados.com.ar,27 de Abril 675 dpto 2,0351 555-1111,NaN
121,ECAM Abogados,"Torre Fragueiro Capitalinas, Humberto 1º 670 P...",0351 483-8070,No hay reseñas
122,José Luis Palazzo | Abogado,Av. Duarte Quirós 515 5C,0351 611-2331,NaN
123,Dr. Oskar Andrés Avalos (abogado),Azpeitia 1698 esquina Urrutia,0351 759-2245,NaN
124,Dra. Doris Navarro - Abogada,Miguel Calixto del Corro 424 Of. 3E,0351 15-672-0896,No hay reseñas

In [56]:
# 1. Verificar valores nulos
nulos = df.isnull()
# 2. Verificar longitud <4 para no nulos
cortos = df.apply(lambda col: col.dropna().astype(str).str.len() < 5)
# Combinar condiciones
df['es_invalida'] = (nulos.all(axis=1) | cortos.all(axis=1))
df

,qBF1Pd,W4Efsd 3,UsdlK,e4rVHe,es_invalida
2,Estudio Juridico Inmobiliario Sanson & Asociados,275 San Jerónimo,0351 422-5646,NaN,False
3,Estudio Jurídico - Laboral Dres. Españon y Bot...,Sucre 135 3 1,0351 514-5620,NaN,False
4,Crucella Estudio de Abogados,Tristán Malbrán 3877,0351 389-7260,NaN,False
5,ROSSI CARRETERO Abogadas,Nicolás Berrotarán 1917 piso 2 Of c,0351 303-2267,NaN,False
6,ARAYA / ABOGADOS,Gdor. Roque Ferreyra 1506,0351 804-2406,NaN,False
...,...,...,...,...,...
120,Jubilados.com.ar,27 de Abril 675 dpto 2,0351 555-1111,NaN,False
121,ECAM Abogados,"Torre Fragueiro Capitalinas, Humberto 1º 670 P...",0351 483-8070,No hay reseñas,False
122,José Luis Palazzo | Abogado,Av. Duarte Quirós 515 5C,0351 611-2331,NaN,False
123,Dr. Oskar Andrés Avalos (abogado),Azpeitia 1698 esquina Urrutia,0351 759-2245,NaN,False
124,Dra. Doris Navarro - Abogada,Miguel Calixto del Corro 424 Of. 3E,0351 15-672-0896,No hay reseñas,False

In [57]:
condicion = df.iloc[:,2].isnull() | (df.iloc[:,2].astype(str).str.len() < 10) | df.iloc[:,-1].astype(bool)
df = df[~condicion]

In [58]:
# df.head()

In [59]:
# col = 'es_invalida'
# col = df.columns[3]
# df = df[~df[col]]
# df

In [60]:
# arreglar numero de telefono
def arreglar_numero (num):
    return re.sub(r'\D', '', str(num))
# [df.iloc[:, 2]]
df.iloc[:, 2] = df.iloc[:, 2].apply(lambda x: arreglar_numero(x))

In [61]:
# Drop column 'ah5Ghc 3' if it exists
df = df.drop(columns=['ah5Ghc 3', 'FQ2IWe src', 'e4rVHe'], axis=1, errors='ignore')
df.head()

,qBF1Pd,W4Efsd 3,UsdlK,es_invalida
2,Estudio Juridico Inmobiliario Sanson & Asociados,275 San Jerónimo,03514225646,False
3,Estudio Jurídico - Laboral Dres. Españon y Bot...,Sucre 135 3 1,03515145620,False
4,Crucella Estudio de Abogados,Tristán Malbrán 3877,03513897260,False
5,ROSSI CARRETERO Abogadas,Nicolás Berrotarán 1917 piso 2 Of c,03513032267,False
6,ARAYA / ABOGADOS,Gdor. Roque Ferreyra 1506,03518042406,False

In [62]:
df.head()

,qBF1Pd,W4Efsd 3,UsdlK,es_invalida
2,Estudio Juridico Inmobiliario Sanson & Asociados,275 San Jerónimo,03514225646,False
3,Estudio Jurídico - Laboral Dres. Españon y Bot...,Sucre 135 3 1,03515145620,False
4,Crucella Estudio de Abogados,Tristán Malbrán 3877,03513897260,False
5,ROSSI CARRETERO Abogadas,Nicolás Berrotarán 1917 piso 2 Of c,03513032267,False
6,ARAYA / ABOGADOS,Gdor. Roque Ferreyra 1506,03518042406,False

In [63]:
df = df.iloc[:, :-1]
columnas_relevantes = ['nombre', 'dir', 'tlf']
df.columns = columnas_relevantes
destino = f'./archivos/{sub}{query}/mod_{archivo}'
# print(destino)
df.to_csv(destino, index=None)

In [64]:
df_result = pd.read_csv(destino)
df_result.head()

,nombre,dir,tlf
0,Estudio Juridico Inmobiliario Sanson & Asociados,275 San Jerónimo,3514225646
1,Estudio Jurídico - Laboral Dres. Españon y Bot...,Sucre 135 3 1,3515145620
2,Crucella Estudio de Abogados,Tristán Malbrán 3877,3513897260
3,ROSSI CARRETERO Abogadas,Nicolás Berrotarán 1917 piso 2 Of c,3513032267
4,ARAYA / ABOGADOS,Gdor. Roque Ferreyra 1506,3518042406